name: idealmart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  iconsax: ^0.0.8
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  http: ^0.13.3
  bloc: ^7.0.0
  flutter_bloc:
  iconly: ^1.0.1
  shared_preferences:
  # The following section is specific to Assets and Fonts

  # For images in the assets directory

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo.png
    - assets/images/intro1.png
    - assets/images/intro2.jpg
    - assets/images/intro3.png
    - assets/images/bg.jpg
    - assets/images/bg2.jpg
